version: '3'
services:
  db:
    image: postgres:latest
    environment:
        - POSTGRES_DB=app
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=supersecretpassword
    ports:
        - "6543:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
